services:
  app:
    container_name: gemini_soa
    build: .
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - app-data:/app/data
      - app-uploads:/app/uploads
    restart: unless-stopped

volumes:
  app-data:
  app-uploads:
